### ISSUE TITLE
Version of GraphViz not specified, could go unstable.  Perhaps make configurable with a default?

### ISSUE THREAD

**Issue by stunney** [ts-graphviz/setup-graphviz#283]
The version of GraphViz is not controlled in this action.  This can lead to unstable and uncontrolled and hard to determine misbehaviour and possible malware introduction (unintended) by the Action.

Suggestion:  Give a default version and allow it to be overridable in configuration by the client.

**Comment by kamiazya** [comment]
@stunney The #340 support allowed us to fix the version so we could address the unfixed risk.

We did not give a default version of Graphviz because it would be difficult to operate updating the version of Graphviz.

**Comment by kamiazya** [comment]
@all-contributors please add @stunney  for ideas
