### ISSUE TITLE
add --yes on sudo apt-get install graphviz libgraphviz-dev pkg-config

### ISSUE THREAD

**Issue by leadelngalame1611** [ts-graphviz/setup-graphviz#321]
Installing dependencies get stocks on Ubuntu 18.0.4
sudo apt-get --yes install graphviz libgraphviz-dev pkg-config

**Comment by kamiazya** [comment]
@leadelngalame1611 It was a hint to solve the issue.

Thanks!

**Comment by kamiazya** [comment]
@all-contributors please add @leadelngalame1611 for bug, ideas
