### ISSUE TITLE
upgrade to node.js v20

### ISSUE THREAD

**Issue by 2bndy5** [ts-graphviz/setup-graphviz#559]
## Is your feature request related to a problem?
GitHub has deprecated actions that use node.js v16. 
https://github.com/ts-graphviz/setup-graphviz/blob/0135b05c0c4c17c48b948c13e1dd530cb2b2a1af/action.yaml#L32

So, we now get the following warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: `ts-graphviz/setup-graphviz@c001ccfb5aff62e28bda6a6c39b59a7e061be5b9`. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Where ts-graphviz/setup-graphviz@c001ccfb5aff62e28bda6a6c39b59a7e061be5b9 points to v1.2.0 (the latest release as of this writing)

## Describe the solution you'd like
Upgrade to node.js v20. I understand this may be easier said than done, but I'm keeping this description simple.

## Describe alternatives you've considered
I could host my own shell script that installs graphviz. But, the TS approach used here would be preferable if we ever decide to use custom docker images in CI.

**Comment by kamiazya** [comment]
@all-contributors please add @2bndy5 for maintenance.
